#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 11 16:46:52 2021

@author: tim
"""


from selenium.webdriver import Firefox
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
from time import sleep
import numpy as np

class BrowserNavigator():
    
    def __init__(self):
        self.currentURL = ""
        try:    
            self.profile = webdriver.FirefoxProfile()
            self.profile.set_preference("browser.download.folderList", 2)
            self.profile.set_preference("browser.download.manager.showWhenStarting", False)
            self.profile.set_preference("browser.download.dir", "/home/tim/Documents/Python Scripts/FTSE100StockData")
            self.profile.set_preference("browser.helperApps.neverAsk.saveToDisk", "text/csv")
            self.browser = Firefox(self.profile)

            #HARDCODED SLEEP BAD BUT HACK FOR NOW
            sleep(5)
        except:
            raise Exception(""" For some reason Selenium Firefox driver failed 
            Check for updates that may have broken the code 
            Check that Geckodriver is in PATH and installed""")

    def navigateToURL(self,URL):
        if(URL == ""):
            raise Exception("You need to provide a URL")            
        try:
            self.browser.get(URL)
            self.currentURL = URL
        except:
            raise Exception(""" Failed to go to that URL, Check you gave valid URL
            Check Wifi and Internet connection""")
    
    def CloseBrowser(self):
        self.browser.close()
        
        
class NavigateYahooFinance(BrowserNavigator):
    def __init__(self):
        BrowserNavigator.__init__(self)
        BrowserNavigator.navigateToURL(self,"https://finance.yahoo.com")
        
        #Deal with terms and conditions popup/iframe
        try:

            self.browser.find_element_by_name("agree").click()
            #HARDCODED SLEEP BAD BUT HACK FOR NOW
            sleep(5)
        except:
            raise Exception("Dealing with Yahoos terms and conditions pop up failed, check if element name is still correct")
            self.browser.close()


    def useYahooSearchBar(self,Input):
        #Current Name of Yahoo search bar
        name="yfin-usr-qry"
        #Needs [0] for reasons that I don't understand unfortunately
        try:
            searchBar = self.browser.find_elements_by_name(name)[0]
        except:
            raise Exception("Failed to find Yahoo Search bar, check if html name has changed")
        sleep(5)
        print(searchBar)
        searchBar.send_keys(Input)
        searchBar.send_keys(Keys.RETURN)

    def clickHistoricalDataButton(self):
        sleep(10)
        try:
            self.browser.find_elements_by_css_selector('li.IbBox:nth-child(5)')[0].click()
            #y = self.browser.find_elements_by_css_selector(css_selector).click()
            sleep(5)
        except:
            raise Exception("Failed to click historical data button, check if xpath has changed")

    def DownloadLastMonthsDataCSV(self):
        try:
            css_selector = "a.Fl\(end\):nth-child(1)"
            self.browser.find_elements_by_css_selector(css_selector)[0].click()
        except:
            raise Exception("DownloadLastMonthsDataCSV failed")



class webscraperFTSE100HistoricalDaily(NavigateYahooFinance):
    
    def __init__(self):
        self.FTSE100List = np.genfromtxt('AuxiliaryCSVFiles/FTSE100Names.csv',delimiter = "'",dtype = str)
        NavigateYahooFinance.__init__(self)
        self.scrapeFTSE100Data()
        
    def scrapeFTSE100Data(self):
        LondonStockExchanceID = ".L"
        for i in np.arange(0,101,1):
            sleep(3)
            Ticker = self.FTSE100List[i] + LondonStockExchanceID
            sleep(5)
            try:
                self.useYahooSearchBar(Ticker)
            except:
                raise Exception("Failed to get {}".format(Ticker))
            sleep(7)
            try:
                self.clickHistoricalDataButton()
            except: 
                raise Exception("clickHistoricalDataButton failed for {}".format(Ticker))
            sleep(10)
            try:
                self.DownloadLastMonthsDataCSV()
            except:
                raise Exception("DownloadLastMonthsDataCSV failed for {}".format(Ticker))
        self.browser.close()

"""

def func():
    x = NavigateYahooFinance()
    sleep(5)bscraper
    x.useYahooSearchBar("III.L")
    sleep(3)
    x.clickHistoricalDataButton()
    sleep(10)
    x.DownloadLastMonthsDataCSV()
    return 0
"""